{
 "title": "ElasticSearch",
 "description": "DIsplay ElasticSearch key metrics from Prometheus",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "3m, 5m, 1h, 6h, 1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(es_cluster_status, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(es_jvm_uptime_seconds{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "shard_type",
    "label": "Shard Type",
    "query": "label_values(es_cluster_shards_number, type)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_status{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "targets": [
    { "expr": "(es_cluster_status == 0) +1", "legendFormat": "GREEN" },
    { "expr": "es_cluster_status == 1", "legendFormat": "YELLOW" },
    { "expr": "(es_cluster_status == 2) - 1", "legendFormat": "RED" }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_nodes_number{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_datanodes_number{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_pending_tasks_number{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$shard_type shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 5 },
     "repeat": "shard_type",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
      }
     ]
    },
    {
     "title": "$shard_type shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4.8, "x": 4.8, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
      }
     ]
    },
    {
     "title": "$shard_type shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4.8, "x": 9.6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
      }
     ]
    },
    {
     "title": "$shard_type shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4.8, "x": 14.399999999999999, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
      }
     ]
    },
    {
     "title": "$shard_type shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4.8, "x": 19.2, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "es_os_cpu_percent",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "es_os_cpu_percent{cluster=\"$cluster\", node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": "es_os_mem_used_bytes",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "es_os_mem_used_bytes{cluster=\"$cluster\", node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "description": "es_fs_path_available_bytes",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk" }
     ],
     "targets": [
      {
       "expr": "1 - es_fs_path_available_bytes{cluster=\"$cluster\",node=~\"$node\"} / es_fs_path_total_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} - {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents indexing rate",
     "type": "graph",
     "description": "es_indices_indexing_index_count",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_indexing_index_count{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Indexing latency",
     "type": "graph",
     "description": "es_indices_indexing_index_time_seconds",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_indexing_index_time_seconds{cluster=\"$cluster\"}[$interval]) / rate(es_indices_indexing_index_count{cluster=\"$cluster\"}[$interval]) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Search rate",
     "type": "graph",
     "description": "es_indices_search_query_count",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Searches/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_search_query_count{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Search latency",
     "type": "graph",
     "description": "es_indices_search_query_time_seconds",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_search_query_time_seconds{cluster=\"$cluster\"}[$interval]) / rate(es_indices_search_query_count{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents count (with replicas)",
     "type": "graph",
     "description": "es_indices_doc_number",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "es_indices_doc_number{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents deleting rate",
     "type": "graph",
     "description": "es_indices_doc_deleted_number",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_doc_deleted_number{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merging rate",
     "type": "graph",
     "description": "es_indices_merges_total_docs_count",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Merges/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_merges_total_docs_count{cluster=\"$cluster\",node=~\".*-d\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "description": "es_indices_fielddata_memory_size_bytes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "es_indices_fielddata_memory_size_bytes{cluster=\"$cluster\", node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "description": "es_indices_fielddata_evictions_count",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_fielddata_evictions_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "description": "es_indices_querycache_cache_size_bytes",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "es_indices_querycache_cache_size_bytes{cluster=\"$cluster\", node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "description": "es_indices_querycache_evictions_count",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_querycache_evictions_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache hits",
     "type": "graph",
     "description": "es_indices_querycache_hit_count",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Hits/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_querycache_hit_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache misses",
     "type": "graph",
     "description": "es_indices_querycache_miss_number",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Misses/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_querycache_miss_number{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing throttling",
     "type": "graph",
     "description": "es_indices_indexing_throttle_time_seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_indexing_throttle_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Merging throttling",
     "type": "graph",
     "description": "es_indices_merges_total_throttled_time_seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_merges_total_throttled_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap used",
     "type": "graph",
     "description": "es_jvm_mem_heap_used_bytes",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Heap" }
     ],
     "targets": [
      {
       "expr": "es_jvm_mem_heap_used_bytes{cluster=\"$cluster\", node=~\"$node\"}",
       "legendFormat": "{{node}} - heap used"
      }
     ]
    },
    {
     "title": "GC Old count",
     "type": "graph",
     "description": "es_jvm_gc_collection_count",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "GC/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_jvm_gc_collection_count{cluster=\"$cluster\",node=~\"$node\",gc=\"old\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GC Old time",
     "type": "graph",
     "description": "es_jvm_gc_collection_time_seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(es_jvm_gc_collection_time_seconds{cluster=\"$cluster\", node=~\"$node\",gc=\"old\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GC Young count",
     "type": "graph",
     "description": "es_jvm_gc_collection_count",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "GC/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_jvm_gc_collection_count{cluster=\"$cluster\",node=~\"$node\",gc=\"young\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GC Young time",
     "type": "graph",
     "description": "es_jvm_gc_collection_time_seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(es_jvm_gc_collection_time_seconds{cluster=\"$cluster\", node=~\"$node\",gc=\"young\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Index Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Index search Query Count",
   "type": "graph",
   "description": "es_index_search_query_count：单个索引查询总量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_query_count{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Search Query Time",
   "type": "graph",
   "description": "es_index_search_query_time_seconds:索引的查询时间",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_query_time_seconds{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Search Fetch Count",
   "type": "graph",
   "description": "es_index_search_fetch_count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_fetch_count{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Search Fetch Time",
   "type": "graph",
   "description": "es_index_search_fetch_time_seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_fetch_time_seconds{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Search Scroll Count",
   "type": "graph",
   "description": "es_index_search_scroll_count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_scroll_count{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Search Scroll Time",
   "type": "graph",
   "description": "es_index_search_scroll_time_seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_search_scroll_time_seconds{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Index Get Missing Count",
   "type": "graph",
   "description": "es_index_get_missing_count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_get_missing_count{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  },
  {
   "title": "Index Get Exists Time",
   "type": "graph",
   "description": "es_index_get_exists_time_seconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(es_index_get_exists_time_seconds{cluster=\"$cluster\"}[$interval]))by(index)",
     "legendFormat": "{{ index }}"
    }
   ]
  }
 ]
}