{
 "title": "Kafka-Qtt-bigdata-kafkaBigTopic-Overview2",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{app=\"kafkaBigTopic\",group=\"bigdata\",service=\"bigdata_jmx_prometheus_javaagent\"},topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores/32",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service =\"bigdata_jmx_prometheus_javaagent\",group=\"bigdata\",app=\"kafkaBigTopic\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{service =\"bigdata_jmx_prometheus_javaagent\",group=\"bigdata\",app=\"kafkaBigTopic\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{service =\"bigdata_jmx_prometheus_javaagent\",group='bigdata',app=\"kafkaBigTopic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"kafkaBigTopic\",group=\"bigdata\",service=\"bigdata_jmx_prometheus_javaagent\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{service =\"bigdata_jmx_prometheus_javaagent\",topic!=\"\",group=\"bigdata\",app=~\"kafkaBigTopic\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{service =\"bigdata_jmx_prometheus_javaagent\",topic!=\"\",group='bigdata',app=~\"kafkaBigTopic\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "description": "kafka_server_brokertopicmetrics_bytesin_total",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{service =\"bigdata_jmx_prometheus_javaagent\",topic!=\"\",group=\"bigdata\",app=~\"kafkaBigTopic\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "description": "kafka_server_brokertopicmetrics_bytesout_total",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{service =\"bigdata_jmx_prometheus_javaagent\",topic!=\"\",group=\"bigdata\",app=~\"kafkaBigTopic\"}[5m]))by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}