{
 "title": "Kafka-Qtt-bigdata-kafkaBigTopic-Overview",
 "description": "Kafka usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partitions{app=\"kafkaBigTopic\",group=\"bigdata\",idc=\"bjf\",topic!='__consumer_offsets'},topic)"
   }
  ]
 },
 "panels": [
  { "title": "Partitons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kafka_topic_partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Topic" },
  {
   "title": "Topic 最初 offset 值",
   "type": "graph",
   "description": "kafka_topic_partition_oldest_offset",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_topic_partition_oldest_offset{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"}) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "生产者topic偏移值",
   "type": "graph",
   "description": "kafka_topic_partition_current_offset",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_topic_partition_current_offset{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"})by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Topic lag 积压",
   "type": "graph",
   "description": "kafka_consumergroup_lag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumergroup_lag{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消费者topic偏移值",
   "type": "graph",
   "description": "kafka_consumergroup_current_offset",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumergroup_current_offset{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=~\"$topic\"})by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "生产消息速率",
   "type": "graph",
   "description": "Rate_produce:  topic_partition_current_offset",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kafka_topic_partition_current_offset{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=~\"$topic\"}[5m]))by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消费消息速率",
   "type": "graph",
   "description": "Rate_Comsumer:  kafka_consumergroup_current_offset",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kafka_consumergroup_current_offset{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Partition Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "kafka_topic_partition_replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_topic_partition_replicas{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_topic_partition_under_replicated_partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_topic_partition_under_replicated_partition{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"})by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_topic_partition_in_sync_replica",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_topic_partition_in_sync_replica{app=\"kafkaBigTopic\",group=\"bigdata\",org=\"qtt\",topic!='__consumer_offsets',topic=\"$topic\"})by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}