{
 "title": "项目nsq监控",
 "tags": [
  "nsq",
  "Secret"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Ip",
    "query": "label_values(up{instance=~\".*\",service=\"nsq\"},instance)"
   },
   {
    "name": "Topic",
    "query": "label_values(nsqd_channel_count{instance=~\".*\",service=\"nsq\"},topic)"
   },
   {
    "name": "Channel",
    "query": "label_values(nsqd_in_flight_count{instance=~\".*\",service=\"nsq\"},channel)"
   },
   { "name": "Rate", "query": "30s,1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "$Ip $Topic Queue Depth",
   "type": "graph",
   "description": "nsqd_depth",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nsqd_depth{topic=~'$Topic'}) by (instance,topic) ",
     "legendFormat": " {{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "$Ip $Topic Inflight",
   "type": "graph",
   "description": "nsqd_in_flight_count",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nsqd_in_flight_count{topic=~'$Topic'}) by (instance,topic) ",
     "legendFormat": "{{ instance }}  {{topic}}"
    }
   ]
  },
  {
   "title": "$Topic Message Count [$Rate]",
   "type": "graph",
   "description": "nsqd_message_count_total",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nsqd_message_count_total{channel=~\"$Channel\",instance=~\"$Ip\",topic=~\"$Topic\",type=\"channel\"}[$Rate])) by (instance,topic,channel)",
     "legendFormat": "{{instance}} - {{topic}} - {{channel}}"
    }
   ]
  },
  {
   "title": "$Topic Timeout Count [$Rate]",
   "type": "graph",
   "description": "nsqd_timeout_count_total",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nsqd_timeout_count_total{channel=~\"$Channel\",instance=~\"$Ip\",topic=~\"$Topic\",type=\"channel\"}[$Rate])) by (instance,topic,channel)",
     "legendFormat": "{{instance}} - {{topic}} - {{channel}}"
    }
   ]
  },
  {
   "title": "$Topic Requeue Count [$Rate]",
   "type": "graph",
   "description": "nsqd_requeue_count_total",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nsqd_requeue_count_total{channel=~\"$Channel\",instance=~\"$Ip\",topic=~\"$Topic\",type=\"channel\"}[$Rate])) by (instance,topic,channel)",
     "legendFormat": "{{instance}} - {{topic}} - {{channel}}"
    }
   ]
  },
  {
   "title": "$Ip Client Count [$Rate]",
   "type": "graph",
   "description": "nsqd_client_count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nsqd_client_count{channel=~\"$Channel\",instance=~\"$Ip\",topic=~\"$Topic\",type=~\"channel\"}[$Rate])) by (instance,topic,channel)",
     "legendFormat": "{{instance}} - {{topic}} - {{channel}}"
    }
   ]
  }
 ]
}